import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import AppProvider from "@/app/AppProvider";
import { cookies } from "next/headers";
import SlideSession from "@/components/slide-session";
import accountApiRequests from "@/apiRequests/account";
import { AccountResType } from "@/schemaValidations/account.schema";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const sessionToken = cookieStore.get("sessionToken")?.value;

    let user: AccountResType["data"] | null = null;
    try {
        if (sessionToken) {
            const data = await accountApiRequests.me(sessionToken);
            user = data.payload.data;
        }
    } catch (error) {
        console.error("Error fetching user data:", error);
    }

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} antialiased`}>
                <Toaster richColors />
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header user={user} />
                    <AppProvider initialSessionToken={sessionToken} user={user}>
                        {children} <SlideSession />
                    </AppProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
